### ISSUE TITLE
ARM64 Windows problem on npm install

### ISSUE THREAD

**Issue by SJang1** [Hoto-Cocoa/Cocoa-Printer-Server#16]
```
npm i

> ghostscript4js@3.1.1 install c:\Cocoa-Printer-Server\node_modules\ghostscript4js
> node-gyp rebuild


c:\Cocoa-Printer-Server\node_modules\ghostscript4js>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\gs\bin\gsdll32.lib
C:\gs\bin\gsdll32.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> c:\Cocoa-Printer-Server\node_modules\ghostscript4js\build\Release\\nothing.lib
  Copying C:/gs/bin/gsdll32.dll to c:\Cocoa-Printer-Server\node_modules\ghostscript4js/build/Release\gsdll32.dll
  The system cannot find the path specified.
  Copying C:/gs/bin/gsdll32.lib to c:\Cocoa-Printer-Server\node_modules\ghostscript4js/build/Release\gsdll32.lib
  The system cannot find the path specified.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238
,5): warning MSB8064: Custom build for item "C:\gs\bin\gsdll32.dll" succeeded, but specified dependency "c:\gs\bin\gsdl
l32.dll" does not exist. This may cause incremental build to work incorrectly. [c:\Cocoa-Printer-Server\node_modules\gh
ostscript4js\build\ghostscript4js.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238
,5): warning MSB8065: Custom build for item "C:\gs\bin\gsdll32.dll" succeeded, but specified output "c:\cocoa-printer-s
erver\node_modules\ghostscript4js\build\release\gsdll32.dll" has not been created. This may cause incremental build to
work incorrectly. [c:\Cocoa-Printer-Server\node_modules\ghostscript4js\build\ghostscript4js.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238
,5): warning MSB8064: Custom build for item "C:\gs\bin\gsdll32.lib" succeeded, but specified dependency "c:\gs\bin\gsdl
l32.lib" does not exist. This may cause incremental build to work incorrectly. [c:\Cocoa-Printer-Server\node_modules\gh
ostscript4js\build\ghostscript4js.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238
,5): warning MSB8065: Custom build for item "C:\gs\bin\gsdll32.lib" succeeded, but specified output "c:\cocoa-printer-s
erver\node_modules\ghostscript4js\build\release\gsdll32.lib" has not been created. This may cause incremental build to
work incorrectly. [c:\Cocoa-Printer-Server\node_modules\ghostscript4js\build\ghostscript4js.vcxproj]
  ghostscript4js.cc
  win_delay_load_hook.cc
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'c:\Cocoa-Printer-Server\node_modules\ghostscript4js\build\Release\gsdll32
.lib' [c:\Cocoa-Printer-Server\node_modules\ghostscript4js\build\ghostscript4js.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
```

**Comment by SJang1** [comment]
```
npm start

> cocoa-printer-server@1.0.0 start c:\Cocoa-Printer-Server
> node index.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'c:\Cocoa-Printer-Server\node_modules\sqlite3\lib\binding\node-v83-win32-ia32\node_sqlite3.node'
Require stack:
- c:\Cocoa-Printer-Server\node_modules\sqlite3\lib\sqlite3.js
- c:\Cocoa-Printer-Server\Database.js
- c:\Cocoa-Printer-Server\ipp-server.js
- c:\Cocoa-Printer-Server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\Cocoa-Printer-Server\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Cocoa-Printer-Server\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'c:\\Cocoa-Printer-Server\\Database.js',
    'c:\\Cocoa-Printer-Server\\ipp-server.js',
    'c:\\Cocoa-Printer-Server\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocoa-printer-server@1.0.0 start: `node index.js`
npm ERR! Exit status 1
```

**Comment by Hoto-Cocoa** [comment]
It seems to npm library ghostscript4js is not supporting ARM64. I will move ghostscript4js to optional dependency.
