### ISSUE TITLE
Invalid key length 

### ISSUE THREAD

**Issue by agustinpallares94** [Hoto-Cocoa/Cocoa-Printer-Server#23]
Hello!
I'm trying to running ir on Mac but i got this error.

`(node:7909) UnhandledPromiseRejectionWarning: Error: Invalid key length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:122:10)
    at IncomingMessage.<anonymous> (/Users/agustinpallares/Downloads/Impresion/Cocoa-Printer-Server/routes/register.post.js:13:54)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Hoto-Cocoa** [comment]
Hi! Sorry for late response.

Did you created `config.json`?
